# Generated by Django 5.1.7 on 2025-03-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
