# Generated by Django 5.1.7 on 2025-04-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad', '0003_usuario_cpf_usuario_tele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.TextField(default=''),
        ),
    ]
